### ISSUE TITLE
Unit of measurement

### ISSUE THREAD

**Issue by lazumbra** [BerAceituno/pcl-conv#1]
In which unit of measurement is the focal lenght saved in csv file of camera poses? Is it in centimeters, millimeters?
If I compute the distance between two points using the XYZ of the camera center. In which unit of measurement I get the result?

**Comment by baceituno** [comment]
The unit of measurement should be the same of the prior format, in the case of .NVM this is given in mts.

**Comment by lazumbra** [comment]
You mean metre–tonne–second?

**Comment by lazumbra** [comment]
I get 1.08 when coimpute distance. Does it mean 1.08 metre–tonne–second? I didn't get what you mean for mts.

**Comment by baceituno** [comment]
metre

**Comment by baceituno** [comment]
Sorry for the confusion
